// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TenantStatus string

const (
	TenantStatusActive    TenantStatus = "active"
	TenantStatusSuspended TenantStatus = "suspended"
	TenantStatusArchived  TenantStatus = "archived"
	TenantStatusPending   TenantStatus = "pending"
)

func (e *TenantStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantStatus(s)
	case string:
		*e = TenantStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantStatus: %T", src)
	}
	return nil
}

type NullTenantStatus struct {
	TenantStatus TenantStatus `json:"tenant_status"`
	Valid        bool         `json:"valid"` // Valid is true if TenantStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TenantStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantStatus), nil
}

type ApiKey struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	Name       pgtype.Text        `db:"name" json:"name"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Revoked    pgtype.Bool        `db:"revoked" json:"revoked"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

type Event struct {
	ID          int64              `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	EventType   pgtype.Text        `db:"event_type" json:"event_type"`
	AggregateID pgtype.UUID        `db:"aggregate_id" json:"aggregate_id"`
	Payload     []byte             `db:"payload" json:"payload"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Task struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	RunID      pgtype.UUID        `db:"run_id" json:"run_id"`
	StepID     string             `db:"step_id" json:"step_id"`
	Status     string             `db:"status" json:"status"`
	WorkerID   pgtype.UUID        `db:"worker_id" json:"worker_id"`
	Attempts   pgtype.Int4        `db:"attempts" json:"attempts"`
	LastError  pgtype.Text        `db:"last_error" json:"last_error"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Result     []byte             `db:"result" json:"result"`
}

type Tenant struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ParentID     pgtype.UUID        `db:"parent_id" json:"parent_id"`
	Slug         string             `db:"slug" json:"slug"`
	Domain       pgtype.Text        `db:"domain" json:"domain"`
	Status       NullTenantStatus   `db:"status" json:"status"`
	Region       pgtype.Text        `db:"region" json:"region"`
	Tier         pgtype.Text        `db:"tier" json:"tier"`
	Settings     []byte             `db:"settings" json:"settings"`
	ContactEmail pgtype.Text        `db:"contact_email" json:"contact_email"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TenantMember struct {
	TenantID pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	UserID   pgtype.UUID        `db:"user_id" json:"user_id"`
	Role     pgtype.Text        `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type UsageRecord struct {
	ID       int64              `db:"id" json:"id"`
	TenantID pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Metric   pgtype.Text        `db:"metric" json:"metric"`
	Value    pgtype.Numeric     `db:"value" json:"value"`
	SampleAt pgtype.Timestamptz `db:"sample_at" json:"sample_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	FullName     pgtype.Text        `db:"full_name" json:"full_name"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Worker struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Name          pgtype.Text        `db:"name" json:"name"`
	Version       pgtype.Text        `db:"version" json:"version"`
	LastHeartbeat pgtype.Timestamptz `db:"last_heartbeat" json:"last_heartbeat"`
	Capacity      []byte             `db:"capacity" json:"capacity"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
}

type Workflow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name       string             `db:"name" json:"name"`
	Version    pgtype.Int4        `db:"version" json:"version"`
	Definition []byte             `db:"definition" json:"definition"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Archived   pgtype.Bool        `db:"archived" json:"archived"`
}

type WorkflowRun struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	WorkflowID pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	Status     string             `db:"status" json:"status"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Payload    []byte             `db:"payload" json:"payload"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
}
