// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantMember = `-- name: AddTenantMember :one
INSERT INTO tenant_members (tenant_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING tenant_id, user_id, role, joined_at
`

type AddTenantMemberParams struct {
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	Role     pgtype.Text `db:"role" json:"role"`
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, addTenantMember, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, contact_email, tier, region, status)
VALUES ($1, $2, $3, $4, $5, 'active')
RETURNING id, name, created_at, parent_id, slug, domain, status, region, tier, settings, contact_email, updated_at
`

type CreateTenantParams struct {
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	ContactEmail pgtype.Text `db:"contact_email" json:"contact_email"`
	Tier         pgtype.Text `db:"tier" json:"tier"`
	Region       pgtype.Text `db:"region" json:"region"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.ContactEmail,
		arg.Tier,
		arg.Region,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.ParentID,
		&i.Slug,
		&i.Domain,
		&i.Status,
		&i.Region,
		&i.Tier,
		&i.Settings,
		&i.ContactEmail,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id
FROM tenants
WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
