// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (TenantMember, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
