// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          int64              `db:"id" json:"id"`
	TenantID    pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	EventType   pgtype.Text        `db:"event_type" json:"event_type"`
	AggregateID pgtype.UUID        `db:"aggregate_id" json:"aggregate_id"`
	Payload     []byte             `db:"payload" json:"payload"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Task struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	RunID      pgtype.UUID        `db:"run_id" json:"run_id"`
	StepID     string             `db:"step_id" json:"step_id"`
	Status     string             `db:"status" json:"status"`
	WorkerID   pgtype.UUID        `db:"worker_id" json:"worker_id"`
	Attempts   pgtype.Int4        `db:"attempts" json:"attempts"`
	LastError  pgtype.Text        `db:"last_error" json:"last_error"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Result     []byte             `db:"result" json:"result"`
}

type Tenant struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	ApiKeyHash  string             `db:"api_key_hash" json:"api_key_hash"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	BillingPlan pgtype.Text        `db:"billing_plan" json:"billing_plan"`
	Quota       []byte             `db:"quota" json:"quota"`
}

type UsageRecord struct {
	ID       int64              `db:"id" json:"id"`
	TenantID pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Metric   pgtype.Text        `db:"metric" json:"metric"`
	Value    pgtype.Numeric     `db:"value" json:"value"`
	SampleAt pgtype.Timestamptz `db:"sample_at" json:"sample_at"`
}

type Worker struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Name          pgtype.Text        `db:"name" json:"name"`
	Version       pgtype.Text        `db:"version" json:"version"`
	LastHeartbeat pgtype.Timestamptz `db:"last_heartbeat" json:"last_heartbeat"`
	Capacity      []byte             `db:"capacity" json:"capacity"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
}

type Workflow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Name       string             `db:"name" json:"name"`
	Version    pgtype.Int4        `db:"version" json:"version"`
	Definition []byte             `db:"definition" json:"definition"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Archived   pgtype.Bool        `db:"archived" json:"archived"`
}

type WorkflowRun struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	TenantID   pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	WorkflowID pgtype.UUID        `db:"workflow_id" json:"workflow_id"`
	Status     string             `db:"status" json:"status"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	Payload    []byte             `db:"payload" json:"payload"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
}
