// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (CreateWorkflowRow, error)
	GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error)
	ListWorkflowsByTenantID(ctx context.Context, arg ListWorkflowsByTenantIDParams) ([]Workflow, error)
}

var _ Querier = (*Queries)(nil)
