// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (id, tenant_id, name, definition)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id, tenant_id, name
`

type CreateWorkflowParams struct {
	TenantID   pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Name       string      `db:"name" json:"name"`
	Definition []byte      `db:"definition" json:"definition"`
}

type CreateWorkflowRow struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Name     string      `db:"name" json:"name"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (CreateWorkflowRow, error) {
	row := q.db.QueryRow(ctx, createWorkflow, arg.TenantID, arg.Name, arg.Definition)
	var i CreateWorkflowRow
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id,
       tenant_id,
       name,
       version,
       definition,
       created_at,
       updated_at,
       archived
FROM workflows
WHERE id = $1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Version,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listWorkflowsByTenantID = `-- name: ListWorkflowsByTenantID :many
SELECT id,
       tenant_id,
       name,
       version,
       definition,
       created_at,
       updated_at,
       archived
FROM workflows
WHERE tenant_id = $1
  AND ((updated_at < $2)
    OR (updated_at = $2 AND id < $3))
ORDER BY updated_at DESC
LIMIT $4
`

type ListWorkflowsByTenantIDParams struct {
	TenantID  pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ID        pgtype.UUID        `db:"id" json:"id"`
	Limit     int32              `db:"limit" json:"limit"`
}

func (q *Queries) ListWorkflowsByTenantID(ctx context.Context, arg ListWorkflowsByTenantIDParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflowsByTenantID,
		arg.TenantID,
		arg.UpdatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Version,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
