// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (GetApiKeyByHashRow, error)
	ListApiKeys(ctx context.Context, tenantID pgtype.UUID) ([]ListApiKeysRow, error)
	RevokeApiKey(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
