// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (tenant_id, key_hash, key_prefix, name)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateApiKeyParams struct {
	TenantID  pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	KeyHash   string      `db:"key_hash" json:"key_hash"`
	KeyPrefix string      `db:"key_prefix" json:"key_prefix"`
	Name      pgtype.Text `db:"name" json:"name"`
}

type CreateApiKeyRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.TenantID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Name,
	)
	var i CreateApiKeyRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, contact_email)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateTenantParams struct {
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	ContactEmail pgtype.Text `db:"contact_email" json:"contact_email"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug, arg.ContactEmail)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
	FullName     pgtype.Text `db:"full_name" json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, tenant_id, revoked, expires_at
FROM api_keys
WHERE key_hash = $1
LIMIT 1
`

type GetApiKeyByHashRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	TenantID  pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Revoked   pgtype.Bool        `db:"revoked" json:"revoked"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (GetApiKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i GetApiKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Revoked,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Email    string      `db:"email" json:"email"`
	FullName pgtype.Text `db:"full_name" json:"full_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return i, err
}

const getUserByEmailWithPassword = `-- name: GetUserByEmailWithPassword :one
SELECT id, email, password_hash
FROM users
WHERE email = $1
`

type GetUserByEmailWithPasswordRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Email        string      `db:"email" json:"email"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
}

func (q *Queries) GetUserByEmailWithPassword(ctx context.Context, email string) (GetUserByEmailWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailWithPassword, email)
	var i GetUserByEmailWithPasswordRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, key_prefix, created_at, last_used_at, revoked, expires_at
FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListApiKeysRow struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	Name       pgtype.Text        `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	Revoked    pgtype.Bool        `db:"revoked" json:"revoked"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ListApiKeys(ctx context.Context, tenantID pgtype.UUID) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysRow
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Revoked,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :exec
UPDATE api_keys
SET revoked = true
WHERE id = $1
`

func (q *Queries) RevokeApiKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeApiKey, id)
	return err
}
